# Generated by Django 4.2.1 on 2023-05-15 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0003_alter_worker_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custommember",
            name="username",
        ),
    ]
