# Generated by Django 4.2.1 on 2023-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0005_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custommember",
            name="is_worker",
            field=models.BooleanField(choices=[(False, "Member"), (True, "Worker")]),
        ),
    ]
