# Generated by Django 4.2.1 on 2023-05-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0006_alter_custommember_is_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="member.category",
            ),
        ),
    ]
