# Generated by Django 4.2.1 on 2023-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0007_worker_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="about_me",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
