# Generated by Django 4.2.1 on 2023-05-22 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0009_custommember_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custommember",
            name="username",
        ),
    ]
