# Generated by Django 4.2.2 on 2023-06-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_worker_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommember',
            name='is_worker',
            field=models.BooleanField(choices=[(False, 'Member'), (True, 'Worker')], default=False),
        ),
    ]
