# Generated by Django 4.2.2 on 2023-06-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_custommember_is_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='category',
            new_name='worker_category',
        ),
    ]
