# Generated by Django 4.2.1 on 2023-05-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0010_remove_custommember_username"),
        ("job", "0002_job_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="worker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="member.worker",
            ),
        ),
    ]
